# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -gladkih@starkovgrp.ru
    on_success: never # default: change
    on_failure: always # default: always
env:
  global:
    - CODECOV_TOKEN="d164c09b-e07a-41c1-8b06-0a2cb4c0ee1f"